server:
  port: 8082

# 建议使用
food:
  rice: 米饭2
  meat: 牛肉2
  sauce:
    - 咖喱
    - 蜜汁
    - 原为

#流式布局方式
#food: {rice: 大米饭,meat: 鸡胸肉}

#使用jasypt加密 encrytor:加密器
jasypt:
  encryptor:
    password: 123456@!
#ENC() 解密
info:
  username: ENC(DZSNMfVw4U7tjalEUqVzOg==)
  password: ENC(9mRG2x17d4ORF7ZECLxakw==)